### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by magnusjjj** [Blackprint/Blackprint#2]
Hi!

I have tried to make the code work, adding the supplied code to the linked scarletframe template.
The furthest I have got to  gives an error of 'Uncaught TypeError: sf.space is not a constructor', and I am at my wits end.

Do you have a sample project planned?

**Comment by StefansArya** [comment]
Hi! thanks for trying Blackprint.
also sorry for late reply.

Blackprint is using ScarletsFrame version `v0.32.3`, I haven't update it for using the `v0.34.9` yet.
Because the framework haven't reach it's stable version, every `v0.*.0` incremental will have some breaking changes so you will need to check the [change log](https://github.com/ScarletsFiction/ScarletsFrame/blob/master/CHANGELOG.md) and specify the fixed version instead of using `latest`.

Feel free to start a new discussion if you encounter an issue, maybe I was missed with something.

I'm planned to create visual scripting available for Pixi.js, Babylon.js, PlayCanvas, and another open source JavaScript library. About the sample project, currently I only have [this example](https://blackprint.github.io/) that already using Pixi.js and SFMediaStream library for the nodes. I will continue Blackprint in near time if I can, maybe around this Saturday.

**Comment by StefansArya** [comment]
Hi,
I have added some example to getting started on the [README.md](https://github.com/Blackprint/Blackprint#example).
If you want to build a custom node, there are a [template](https://github.com/Blackprint/template-js) that you can use.

If you have some other question, feel free to open a new discussion or join the Discord. Good luck!
